let sea = {
  front: "🌊",
  frontColor: "background: linear-gradient(315deg, #8DB7F5 25%, #6068ff 25%)",

  back: [
    "🦐",
    "🦀",
    "🪼",
    "🪸",
    "🐡",
    "🐳",
    "🦈",
    "🐚",
    "🐠",
    "🐟",
    "🐬",
    "🐋",
    "🦞",
    "🐙",
    "🏄‍♀️",
    "⛵️",
    "🚣‍♂️",
    "🛟",
  ],
  backColor: "background: linear-gradient(315deg, #8DB7F5 25%, #8DB7F5 25%);",
};

let spring = {
  front: "🪷",
  frontColor: "background: linear-gradient(315deg, #F5ADD7 25%, #db3998 25%)",
  back: [
    "🌷",
    "🌹",
    "🦋",
    "🪻",
    "🌼",
    "🌻",
    "🐞",
    "🌿",
    "🦗",
    "🪲",
    "🐝",
    "🪱",
    "🐛",
    "🐜",
    "🌾",
    "💐",
    "🪰",
    "🪲",
  ],
  backColor: "background: linear-gradient(315deg, #F5ADD7 25%, #F5ADD7 25%)",
};

let mountain = {
  front: "🏞",
  frontColor: "background: linear-gradient(315deg, #7ACD93 25%, #206936 25%)",
  back: [
    "🪵",
    "🌳",
    "🪨",
    "🍄",
    "🐻",
    "🐎",
    "🏕",
    "🦉",
    "🧗‍♂️",
    "🏔",
    "🗻",
    "🚵‍♂️",
    "🦫",
    "🍄‍🟫",
    "🍂",
    "🍃",
    "🌱",
    "🌄",
  ],
  backColor: "background: linear-gradient(315deg, #7ACD93 25%, #7ACD93 25%)",
};

let universe = {
  front: "🌌",
  frontColor: "background: linear-gradient(315deg, #8486DF 25%, #51539f 25%)",
  back: [
    "☄️",
    "🌑",
    "🌏",
    "🪐",
    "💫",
    "🛸",
    "☀️",
    "✨",
    "🦠",
    "🔭",
    "📡",
    "🚀",
    "🛰",
    "🌛",
    "⚡️",
    "🌓",
    "🎆",
    "🌕",
  ],
  backColor: "background: linear-gradient(315deg, #8486DF 25%, #8486DF 25%)",
};

let animals = {
  front: "🐾",
  frontColor:
    "background: linear-gradient(315deg, hsl(45, 52%, 43%) 25%, hsl(48, 54%, 15%) 25%)",
  back: [
    "🐊",
    "🐅",
    "🐆",
    "🦓",
    "🫏",
    "🦍",
    "🦧",
    "🦣",
    "🐖",
    "🐏",
    "🫎",
    "🐫",
    "🦒",
    "🦘",
    "🐒",
    "🐄",
    "🦥",
    "🦅",
  ],
  backColor:
    "background: linear-gradient(315deg, hsl(45, 52%, 43%) 25%,hsl(45, 52%, 43%) 25%)",
};

export { sea, mountain, universe, spring, animals };